apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-hello
  template:
    metadata:
      labels:
        app: node-hello
    spec:
      containers:
        - name: node-hello
          image: mikedev80/node-hello
          ports:
            - containerPort: 3030